### ISSUE TITLE
[Bug Report] 执行报错

### ISSUE THREAD

**Issue by RimuruW** [anwenhu/zhixuewang-python#30]
登录后按照 Wiki 查询最新成绩，报错如下
```python
>>> print(zxw.get_self_mark())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/zhixuewang/student/student.py", line 221, in get_self_mark
    exam = self.get_exam(exam_data)
  File "/usr/lib/python3.9/site-packages/zhixuewang/student/student.py", line 109, in get_exam
    return self.get_latest_exam()
  File "/usr/lib/python3.9/site-packages/zhixuewang/student/student.py", line 151, in get_latest_exam
    exams = self.__get_page_exam(1)
  File "/usr/lib/python3.9/site-packages/zhixuewang/student/student.py", line 134, in __get_page_exam
    json_data = r.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by aquamarine5** [comment]
https://github.com/anwenhu/zhixuewang-python/pull/32
我已经对此修复
