### ISSUE TITLE
考试成绩没有全部出来时会报错

### ISSUE THREAD

**Issue by SherkeyXD** [anwenhu/zhixuewang-python#35]
报错如下 
Traceback (most recent call last):
  File "E:\VSCodeFiles\Python\zhixuewang\zxw.py", line 94, in <module>
    print(zxw.get_self_mark(exam))
  File "E:\VSCodeFiles\Python\zhixuewang\venv\lib\site-packages\zhixuewang\student\student.py", line 223, in get_self_mark
    return self.__get_self_mark(exam, has_total_score)
  File "E:\VSCodeFiles\Python\zhixuewang\venv\lib\site-packages\zhixuewang\student\student.py", line 190, in __get_self_mark
    total_score = json_data["totalScore"]
KeyError: 'totalScore'

**Comment by SherkeyXD** [comment]
这个问题以前也出现过
还有现在似乎查不到年段排名了（之前可以
